/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as AppRouteImport } from './routes/_app';
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password';
import { Route as LoginRouteImport } from './routes/login';
import { Route as RegisterRouteImport } from './routes/register';
import { Route as ResetPasswordRouteImport } from './routes/reset-password';
import { Route as AppIndexRouteImport } from './routes/_app.index';
import { Route as AppStatusRouteImport } from './routes/_app.status';
import { Route as InvitationsAcceptRouteImport } from './routes/invitations.accept';
import { Route as AppMembersInviteRouteImport } from './routes/_app.members.invite';

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any);
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any);
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any);
const AppStatusRoute = AppStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AppRoute,
} as any);
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any);
const AppMembersInviteRoute = AppMembersInviteRouteImport.update({
  id: '/members/invite',
  path: '/members/invite',
  getParentRoute: () => AppRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/status': typeof AppStatusRoute;
  '/invitations/accept': typeof InvitationsAcceptRoute;
  '/members/invite': typeof AppMembersInviteRoute;
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/status': typeof AppStatusRoute;
  '/invitations/accept': typeof InvitationsAcceptRoute;
  '/': typeof AppIndexRoute;
  '/members/invite': typeof AppMembersInviteRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_app': typeof AppRouteWithChildren;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/_app/status': typeof AppStatusRoute;
  '/invitations/accept': typeof InvitationsAcceptRoute;
  '/_app/': typeof AppIndexRoute;
  '/_app/members/invite': typeof AppMembersInviteRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/status'
    | '/invitations/accept'
    | '/members/invite';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/status'
    | '/invitations/accept'
    | '/'
    | '/members/invite';
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_app/status'
    | '/invitations/accept'
    | '/_app/'
    | '/_app/members/invite';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren;
  ForgotPasswordRoute: typeof ForgotPasswordRoute;
  LoginRoute: typeof LoginRoute;
  RegisterRoute: typeof RegisterRoute;
  ResetPasswordRoute: typeof ResetPasswordRoute;
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/forgot-password': {
      id: '/forgot-password';
      path: '/forgot-password';
      fullPath: '/forgot-password';
      preLoaderRoute: typeof ForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/register': {
      id: '/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/reset-password': {
      id: '/reset-password';
      path: '/reset-password';
      fullPath: '/reset-password';
      preLoaderRoute: typeof ResetPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_app/': {
      id: '/_app/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AppIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/status': {
      id: '/_app/status';
      path: '/status';
      fullPath: '/status';
      preLoaderRoute: typeof AppStatusRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/invitations/accept': {
      id: '/invitations/accept';
      path: '/invitations/accept';
      fullPath: '/invitations/accept';
      preLoaderRoute: typeof InvitationsAcceptRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_app/members/invite': {
      id: '/_app/members/invite';
      path: '/members/invite';
      fullPath: '/members/invite';
      preLoaderRoute: typeof AppMembersInviteRouteImport;
      parentRoute: typeof AppRoute;
    };
  }
}

interface AppRouteChildren {
  AppStatusRoute: typeof AppStatusRoute;
  AppIndexRoute: typeof AppIndexRoute;
  AppMembersInviteRoute: typeof AppMembersInviteRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppStatusRoute: AppStatusRoute,
  AppIndexRoute: AppIndexRoute,
  AppMembersInviteRoute: AppMembersInviteRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
