/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as AppRouteImport } from './routes/_app';
import { Route as LoginRouteImport } from './routes/login';
import { Route as RegisterRouteImport } from './routes/register';
import { Route as AppIndexRouteImport } from './routes/_app.index';
import { Route as AppStatusRouteImport } from './routes/_app.status';
import { Route as InvitationIndexRouteImport } from './routes/invitation.index';
import { Route as InvitationAcceptedRouteImport } from './routes/invitation.accepted';
import { Route as OnboardingPasswordRouteImport } from './routes/onboarding.password';
import { Route as OnboardingSignInRouteImport } from './routes/onboarding.sign-in';
import { Route as AppMembersInviteRouteImport } from './routes/_app.members.invite';

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any);
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any);
const AppStatusRoute = AppStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AppRoute,
} as any);
const InvitationIndexRoute = InvitationIndexRouteImport.update({
  id: '/invitation/',
  path: '/invitation/',
  getParentRoute: () => rootRouteImport,
} as any);
const InvitationAcceptedRoute = InvitationAcceptedRouteImport.update({
  id: '/invitation/accepted',
  path: '/invitation/accepted',
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingPasswordRoute = OnboardingPasswordRouteImport.update({
  id: '/onboarding/password',
  path: '/onboarding/password',
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingSignInRoute = OnboardingSignInRouteImport.update({
  id: '/onboarding/sign-in',
  path: '/onboarding/sign-in',
  getParentRoute: () => rootRouteImport,
} as any);
const AppMembersInviteRoute = AppMembersInviteRouteImport.update({
  id: '/members/invite',
  path: '/members/invite',
  getParentRoute: () => AppRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/status': typeof AppStatusRoute;
  '/invitation/accepted': typeof InvitationAcceptedRoute;
  '/onboarding/password': typeof OnboardingPasswordRoute;
  '/onboarding/sign-in': typeof OnboardingSignInRoute;
  '/invitation/': typeof InvitationIndexRoute;
  '/members/invite': typeof AppMembersInviteRoute;
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/status': typeof AppStatusRoute;
  '/invitation/accepted': typeof InvitationAcceptedRoute;
  '/onboarding/password': typeof OnboardingPasswordRoute;
  '/onboarding/sign-in': typeof OnboardingSignInRoute;
  '/': typeof AppIndexRoute;
  '/invitation': typeof InvitationIndexRoute;
  '/members/invite': typeof AppMembersInviteRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_app': typeof AppRouteWithChildren;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/_app/status': typeof AppStatusRoute;
  '/invitation/accepted': typeof InvitationAcceptedRoute;
  '/onboarding/password': typeof OnboardingPasswordRoute;
  '/onboarding/sign-in': typeof OnboardingSignInRoute;
  '/_app/': typeof AppIndexRoute;
  '/invitation/': typeof InvitationIndexRoute;
  '/_app/members/invite': typeof AppMembersInviteRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/status'
    | '/invitation/accepted'
    | '/onboarding/password'
    | '/onboarding/sign-in'
    | '/invitation/'
    | '/members/invite';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/login'
    | '/register'
    | '/status'
    | '/invitation/accepted'
    | '/onboarding/password'
    | '/onboarding/sign-in'
    | '/'
    | '/invitation'
    | '/members/invite';
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/status'
    | '/invitation/accepted'
    | '/onboarding/password'
    | '/onboarding/sign-in'
    | '/_app/'
    | '/invitation/'
    | '/_app/members/invite';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  RegisterRoute: typeof RegisterRoute;
  InvitationAcceptedRoute: typeof InvitationAcceptedRoute;
  OnboardingPasswordRoute: typeof OnboardingPasswordRoute;
  OnboardingSignInRoute: typeof OnboardingSignInRoute;
  InvitationIndexRoute: typeof InvitationIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/register': {
      id: '/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_app/': {
      id: '/_app/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AppIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/status': {
      id: '/_app/status';
      path: '/status';
      fullPath: '/status';
      preLoaderRoute: typeof AppStatusRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/invitation/': {
      id: '/invitation/';
      path: '/invitation';
      fullPath: '/invitation/';
      preLoaderRoute: typeof InvitationIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/invitation/accepted': {
      id: '/invitation/accepted';
      path: '/invitation/accepted';
      fullPath: '/invitation/accepted';
      preLoaderRoute: typeof InvitationAcceptedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/onboarding/password': {
      id: '/onboarding/password';
      path: '/onboarding/password';
      fullPath: '/onboarding/password';
      preLoaderRoute: typeof OnboardingPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/onboarding/sign-in': {
      id: '/onboarding/sign-in';
      path: '/onboarding/sign-in';
      fullPath: '/onboarding/sign-in';
      preLoaderRoute: typeof OnboardingSignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_app/members/invite': {
      id: '/_app/members/invite';
      path: '/members/invite';
      fullPath: '/members/invite';
      preLoaderRoute: typeof AppMembersInviteRouteImport;
      parentRoute: typeof AppRoute;
    };
  }
}

interface AppRouteChildren {
  AppStatusRoute: typeof AppStatusRoute;
  AppIndexRoute: typeof AppIndexRoute;
  AppMembersInviteRoute: typeof AppMembersInviteRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppStatusRoute: AppStatusRoute,
  AppIndexRoute: AppIndexRoute,
  AppMembersInviteRoute: AppMembersInviteRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  InvitationAcceptedRoute: InvitationAcceptedRoute,
  OnboardingPasswordRoute: OnboardingPasswordRoute,
  OnboardingSignInRoute: OnboardingSignInRoute,
  InvitationIndexRoute: InvitationIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
